CREATE TABLE IF NOT EXISTS customers(
  id            UUID PRIMARY KEY,
  email     VARCHAR(255) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  status    VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP  NOT NULL DEFAULT NOW()
);

ikd´jlkfj