CREATE TABLE IF NOT EXISTS products(
  id        UUID PRIMARY KEY,
  name      VARCHAR(255) UNIQUE NOT NULL,
  price     NUMERIC(10,2) NOT NULL,
  currency  CHAR(3) NOT NULL DEFAULT 'USD',
  status    VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP  NOT NULL DEFAULT NOW()
);